<?php
	$js_files = array(
		array( "js/" , "LinkedList.js"),
		array( "js/" , "Handler.js"),
		
		array( "js/chardev_lib/" , "Globals.js"),
		array( "js/chardev_lib/" , "TextIO.js"),
		array( "js/chardev_lib/" , "CharacterIO.js"),
		array( "js/chardev_lib/" , "DatabaseIO.js"),
		array( "js/chardev_lib/" , "GameInfo.js"),
		array( "js/chardev_lib/" , "Listener.js"),
		array( "js/chardev_lib/" , "Tools.js"),
		array( "js/chardev_lib/" , "Tooltip.js"),
		
		array( "js/evolution/" , "JobManager.js"),
		array( "js/evolution/" , "GeneticAlgorithm.js"),
		array( "js/evolution/" , "GAIndividual.js"),
		
		array( "js/chardev_lib/" , "ReforgeOptimiser.js"),
		array( "js/chardev_lib/" , "EventManager.js"),
		
		array( "js/chardev_lib/" , "ItemRandomEnchantment.js"),
		array( "js/chardev_lib/" , "ItemRandomProperty.js"),
		array( "js/chardev_lib/" , "ItemRandomSuffix.js"),
		array( "js/chardev_lib/" , "ItemSet.js"),
		array( "js/chardev_lib/" , "GemProperties.js"),
		array( "js/chardev_lib/" , "Item.js"),
		
		array( "js/chardev_lib/" , "SkillLine.js"),
		array( "js/chardev_lib/" , "Shapeform.js"),
		array( "js/chardev_lib/" , "SpellEffect.js"),
		array( "js/chardev_lib/" , "SpellScaling.js"),
		array( "js/chardev_lib/" , "SpellAuraOptions.js"),
		array( "js/chardev_lib/" , "SpellClassOptions.js"),
		array( "js/chardev_lib/" , "SpellEquippedItems.js"),
		array( "js/chardev_lib/" , "SpellShapeshift.js"),
		array( "js/chardev_lib/" , "Spell.js"),
		array( "js/chardev_lib/" , "SpellItemEnchantment.js"),
		
		array( "js/chardev_lib/" , "Profession.js"),
		
		array( "js/gui_lib/", "Collapsable.js"),
		array( "js/gui_lib/", "LayeredDiv.js"),
		array( "js/gui_lib/", "Menu.js"),
		array( "js/gui_lib/", "SingleSelect.js"),
		array( "js/gui_lib/", "MultiSelect.js"),
		array( "js/gui_lib/", "StackedDiv.js"),
		array( "js/gui_lib/", "StaticGrid.js"),
		array( "js/gui_lib/", "TabFolder.js"),
		array( "js/gui_lib/" , "Overlay.js"),
		array( "js/gui_lib/" , "FilterableCollection.js"),
		
		array( "js/chardev_lib/container/" , "Container.js"),
		array( "js/chardev_lib/container/" , "ItemContainer.js"),
		array( "js/chardev_lib/container/" , "SpellContainer.js"),
		
		array( "js/chardev_lib/" , "Stats.js"),
		array( "js/chardev_lib/" , "Inventory.js"),
		array( "js/chardev_lib/" , "CharacterRace.js"),
		array( "js/chardev_lib/" , "Talent.js"),
		array( "js/chardev_lib/" , "Talents.js"),
		array( "js/chardev_lib/" , "CharacterClass.js"),
		array( "js/chardev_lib/" , "Auras.js"),
		array( "js/chardev_lib/" , "Character.js"),
		array( "js/chardev_lib/" , "Glyph.js"),
		array( "js/chardev_lib/" , "Buff.js"),
		array( "js/chardev_lib/" , "Buffs.js"),
		
		array( "js/chardev_lib/gui/" , "StatWeightInterface.js"),
		array( "js/chardev_lib/gui/" , "ReforgeOptimisationInterface.js"),
		array( "js/chardev_lib/gui/" , "ReforgeInterface.js"),
		array( "js/chardev_lib/gui/" , "SocketInterface.js"),
		array( "js/chardev_lib/gui/" , "GlyphInterface.js"),
		array( "js/chardev_lib/gui/" , "BuffInterface.js"),
		array( "js/chardev_lib/gui/" , "RandomPropertyInterface.js"),
		array( "js/chardev_lib/gui/" , "Stat.js"),
		array( "js/chardev_lib/gui/" , "ItemSlot.js"),
		array( "js/chardev_lib/gui/" , "ShapeSelector.js"),
		array( "js/chardev_lib/gui/" , "PresenceSelector.js"),
		array( "js/chardev_lib/gui/" , "RaceClassSelector.js"),
		array( "js/chardev_lib/gui/" , "BuffBar.js"),
		array( "js/chardev_lib/gui/" , "CharacterSheet.js"),
		
		array( "js/chardev_lib/gui/list/" , "FilterManager.js"),
		array( "js/chardev_lib/gui/list/" , "Filter.js"),
		array( "js/chardev_lib/gui/list/" , "ItemFilter.js"),
		array( "js/chardev_lib/gui/list/" , "SetFilter.js"),
		array( "js/chardev_lib/gui/list/" , "SpellFilter.js"),
		array( "js/chardev_lib/gui/list/" , "ProfileFilter.js"),
		array( "js/chardev_lib/gui/list/" , "StatWeightsFilter.js"),
		
		array( "js/chardev_lib/gui/list/" , "List.js"),
		array( "js/chardev_lib/gui/list/" , "ItemList.js"),
		array( "js/chardev_lib/gui/list/" , "SetList.js"),
		array( "js/chardev_lib/gui/list/" , "SpellList.js"),
		array( "js/chardev_lib/gui/list/" , "ProfileList.js"),
		array( "js/chardev_lib/gui/list/" , "StatWeightsList.js"),
		
		array( "js/chardev_lib/gui/" , "TalentIcon.js"),
		array( "js/" , "Gui.js"),
		array( "js/" , "Ajax.js"),
		array( "js/" , "Chardev.js"),
		array( "js/" , "Engine.js")
	);
?>