<?php

use chardev\Chardev;
use chardev\ChardevHelper;
use chardev\FormatHelper;
use chardev\Language;
use chardev\Session;
use chardev\TemplateHelper;
use chardev\backend\UserDatabase;

$ci = Chardev::getInstance();
$showAds = $ci->showAds();
$hideGoogle = $ci->hideGoogle();

$view = $th->getTemplate();
$basePath = TemplateHelper::getBasePath();

$loggedInUser = Session::getLoggedInUser();

?>
<?php echo '<?xml version="1.0" encoding="utf-8" ?>' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
    <link rel="icon" href="/images/site/favico.png" type="image/png"/>
    <title>chardev 10 - Mist of Pandaria - BETA</title>

    <script type="text/javascript">
        /* <![CDATA[ */
        var locale = <?php echo json_encode( Language::getInstance()->getLocaleArray()) ?>;
        /* ]]> */
    </script>

    <?php echo $th->getHeadLinks() ?>

    <script type="text/javascript">
        /* <![CDATA[ */
        var g_settings = {
            character: null,
            language: 'en',
            sessionId: '',
            user: 0,
            isPlanner: false
        };

        var g_realmList = {};

        $(function () {
            Tooltip.initialise();

            if (window['CHARDEV_CORE_BUILD']) {
                document.getElementById('chardev_core_version').innerHTML = window['CHARDEV_CORE_BUILD'];
            }
        });
        /* ]]> */
    </script>



    <?php

    $jsSettings = array(
        "user" => null,
        "language" => Language::getInstance()->toSuffixString(),
        "debug" => isset($_GET['debug'])
    );

    if ($loggedInUser) {
        $jsSettings["sessionId"] = session_id();
        $jsSettings["user"] = $loggedInUser->getJsUserData();
    }

    ?>
    <script type='text/javascript'>
        /* <![CDATA[ */
        g_settings = <?php echo json_encode($jsSettings) ?>;
        if(g_settings.user) {
            g_settings.user = new User(g_settings.user);
        }
        g_realmList = <?php echo json_encode(UserDatabase::getInstance()->getRealmList()); ?>;
        /* ]]> */
    </script>
</head>
<body onload="">

<div id="tt_wrapper">
    <div class="tt_overlay_w" id="tt_overlay_w">
        <div class="tt_overlay" id="tt_overlay"></div>
    </div>
    <div class="ix_header">

        <div class="ix_center ix_logo">
            <div class="ix_center ix_main_menu">
                <div class="ix_mm_entry"><a
                        class="ix_mm_link<?php echo $view == 'Index' ? " ix_mm_link_active" : ""; ?>"
                        href="http://chardev.org/Index.html"><span class="ix_mm_ll">home</span></a></div>
                <div class="ix_mm_entry"><a
                        class="ix_mm_link<?php echo $view == 'Planner' ? " ix_mm_link_active" : ""; ?>"
                        href="<?php echo $basePath ?>Planner.html"><span class="ix_mm_ll">planner</span></a></div>
                <div class="ix_mm_entry"><a
                        class="ix_mm_link<?php echo $view == 'Forum' ? " ix_mm_link_active" : ""; ?>"
                        href="<?php echo $basePath ?>Forum.html"><span class="ix_mm_ll">forum</span></a></div>
                <div class="ix_mm_entry"><a
                        class="ix_mm_link<?php echo $view == 'Donate' ? " ix_mm_link_active" : ""; ?>"
                        href="<?php echo $basePath ?>Donate.html"><span class="ix_mm_ll">donate</span></a></div>
<?php if( ! Session::loggedIn()): ?>
                <div class="ix_mm_entry"><a
                        class="ix_mm_link<?php echo $view == 'Register' ? " ix_mm_link_active" : ""; ?>"
                        href="<?php echo $basePath ?>Register.html"><span class="ix_mm_ll">register</span></a></div>
<?php endif; ?>
                <div class="ix_mm_entry"><a class="ix_mm_link"
                                            href="https://github.com/chardev/chardev9/tree/chardev10"><span
                            class="ix_mm_ll">source</span></a></div>
                <div style="clear:both"></div>
            </div>
            <?php
            if ($view != 'Login' && $view != 'Logout') :
                $isPlanner = $view == 'Planner';
                ?>

                <form id='ix_login_form' <?php echo ! Session::loggedIn() ? '' : 'style="display:none;"' ?>
                      onsubmit="<?php echo $isPlanner ? 'Chardev.login(); return false;' : 'return Chardev.validateLogin();' ?>"
                      action="<?php echo $isPlanner ? 'javascript:;' : $basePath . 'Login.html' ?>" method="post">
                    <div class="ix_login_input_container">
                        <div class='ix_login_note'>&nbsp;</div>
                        <input tabindex="3"
                               class="button button_dark"
                               onmouseout="this.className='button button_dark'"
                               onmouseover="this.className='button button_dark button_dark_hover'"
                               type="submit"
                               value="Log in"
                            />
                    </div>
                    <div class="ix_login_input_container">
                        <div class='ix_login_note'><label for="login_password">Password:</label></div>
                        <input tabindex="2" id="login_password" type="password" class="input ix_login_input"/>
                        <input type="hidden" id="login_password_md5" name="login_password"/>

                        <div class='ix_add_options'><a href="<?php echo $basePath ?>RecoverPassword.html">Forgot your
                                password?</a></div>
                    </div>
                    <div class="ix_login_input_container">
                        <div class='ix_login_note'><label for="login_user_name">User Name:</label></div>
                        <input
                            tabindex="1" <?php if (isset($_POST['login_user_name'])) echo "value='" . $_POST['login_user_name'] . "'" ?>
                            class="input ix_login_input" id="login_user_name" name="login_user_name"/>

                        <div>
                            <span class='ix_add_options'><label for="login_cookie">Stay logged in:</label></span>
                            <input tabindex="4" type="checkbox" checked="checked" id="login_cookie" name="login_cookie"
                                   class="ix_stay_logged_in"/>
                            <input name="redirect_url" type="hidden"
                                   value="<?php echo FormatHelper::getRedirectUrl(); ?>"/>
                        </div>
                    </div>
                </form>

                <form id='ix_logout_form' <?php echo Session::loggedIn() ? '' : 'style="display:none;"' ?>
                      onsubmit="<?php echo $isPlanner ? 'Chardev.logout(); return false;' : '' ?>"
                      action="<?php echo $isPlanner ? 'javascript:;' : $basePath ?>" method="post">
                    <div style='width: 60px; float: left; padding-left: 55px; padding-top: 11px;'>
                        <?php if (!$hideGoogle): ?>
                            <!--							<g:plusone size="medium" href="http://chardev.org/"></g:plusone>-->
                            <!--							<script type="text/javascript">-->
                            <!--							  window.___gcfg = {lang: 'en-GB'};-->
                            <!--							-->
                            <!--							  (function() {-->
                            <!--							    var po = document.createElement('script'); po.type = 'text/javascript'; po.async = true;-->
                            <!--							    po.src = 'https://apis.google.com/js/plusone.js';-->
                            <!--							    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(po, s);-->
                            <!--							  })();-->
                            <!--							</script>-->
                        <?php endif; ?>
                    </div>

                    <div class='ix_login_input_container'>
                        <div class='ix_login_note'>&nbsp;</div>
                        <input value="Log out" type="submit" class="button button_dark"
                               onmouseout="this.className='button button_dark'"
                               onmouseover="this.className='button button_dark button_dark_hover'"/>
                        <input name='redirect_url' type='hidden'
                               value='<?php echo FormatHelper::getRedirectUrl(); ?>'/>
                        <input name='logout' type='hidden'/>
                    </div>
                    <div class='ix_login_input_container'>
                        <div class='ix_login_note'>You are logged in as</div>
                        <?php
                        if ($loggedInUser):
                            ?>
                            <a id='ix_self_link' href="<?php echo ChardevHelper::getUserUrl($loggedInUser)?>"
                               class='ix_self_link'><?php echo $loggedInUser->getName()?></a>
                        <?php else:
                            ?>
                            <a id='ix_self_link' class='ix_self_link'></a>
                        <?php
                        endif;
                        ?>
                    </div>
                </form>
            <?php
            endif;
            ?>
            <div style="clear:both"></div>
        </div>
    </div>

    <div class="ix_center ix_w">
        <div class="ix_content_w">
            <div class="cp_mm_p" id="mtf_p"></div>
            <?php if ($showAds && !$hideGoogle) : ?>
                <div style="position: relative; top: 0; left: 0;">
                    <div id="ix_ad_v" class="ix_ad_v">
                        <script type="text/javascript"><!--
                            google_ad_client = "ca-pub-7339088166028367";
                            /* 160x600, Erstellt 01.12.10 */
                            google_ad_slot = "9407904006";
                            google_ad_width = 160;
                            google_ad_height = 600;
                            //-->
                        </script>
                        <script type="text/javascript"
                                src="http://pagead2.googlesyndication.com/pagead/show_ads.js">
                        </script>
                    </div>
                </div>
            <?php endif;?>
            <div class="ix_content_p">
                <div class="ix_content_b">
                    <div class="ix_content" id="content">

                        <noscript>
                            <div class='ix_noscript'>JavaScript is Disabled!</div>
                        </noscript>

                        <?php echo $th->getContent() ?>
                    </div>
                </div>
            </div>
        </div>
        <div class="ix_foot">

            <?php if ($showAds && !$hideGoogle) : ?>
                <div id='ix_ad_h' class='ix_ad_h'>
                    <script type='text/javascript'><!--
                        google_ad_client = 'pub-7339088166028367';
                        google_ad_slot = '8748092503';
                        google_ad_width = 728;
                        google_ad_height = 90;
                        //-->
                    </script>
                    <script type='text/javascript'
                            src='http://pagead2.googlesyndication.com/pagead/show_ads.js'>
                    </script>
                </div>
            <?php endif;?>

            <div class="ix_bottom_link_bar">
                <a class="ix_bottom_link" href='<?php echo $basePath . 'Items.html'?>'>Items</a>
                <a class="ix_bottom_link" href='<?php echo $basePath . 'Spells.html'?>'>Spells</a>
                <a class="ix_bottom_link" href='<?php echo $basePath . 'BaseStats.html'?>'>Base Stats</a>
                <a class="ix_bottom_link" href='<?php echo $basePath . 'Talents.html'?>'>Talent Planner</a>

                <a class="ix_bottom_link" href='<?php echo $basePath . 'Credits.html'?>'>Credits</a>
                <a class="ix_bottom_link" href='<?php echo $basePath . 'SiteNotice.html'?>'>Site Notice</a>
                <a class="ix_bottom_link" href='http://wotlk.chardev.org/?character'>Pre 4.0.1 chardev</a>
                <a class="ix_bottom_link" href='http://cata.chardev.org/?character'>Pre 5.0.1 chardev</a>
            </div>
            <div class="ix_copy">&copy; 2007-2013 chardev.org - Design and Code by Martin Wa&szlig;mann -
                Build:10.0b<span id='chardev_core_version'></span></div>
            <div class="ix_disclaimer">World of Warcraft and Blizzard Entertainment are trademarks or registered
                trademarks of Blizzard Entertainment in the U.S. and/or other countries.
            </div>
        </div>
    </div>
</div>
<?php if (!$hideGoogle): ?>
    <script type="text/javascript">
    //<!--
        var _gaq = _gaq || [];
        _gaq.push(['_setAccount', 'UA-5069604-2']);
        _gaq.push(['_trackPageview']);

        (function() {
            var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
            ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
            var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
        })();
    //-->
    </script>
<?php endif; ?>
</body>
</html>