<?php

	use chardev\backend\UserDatabase;
	use chardev\backend\UserManager;
	use chardev\backend\DoesNotExistException;

	$step = 1;
	$error = "";

	if( isset($_POST['recover_new_password']) && isset($_POST['recover_token']) ) {
		if( ! UserManager::getInstance()->validateRecoveryToken($_POST['recover_token']) ) {
			$error = "The given token is invalid or outdated!";
		}
		else {
			$arr = UserManager::getInstance()->parseRecoveryToken($_POST['recover_token']);
			if( strlen($_POST['recover_new_password']) != 32 ) {
				$error = "Given password is not a valid hash!";
			} 
			else {
				UserDatabase::getInstance()->changePassword( $arr["user_id"], $_POST['recover_new_password'] );
				header("Location: Login.html?Recovery");
			}
		}
	}
	else if( isset($_GET['token'])) {

		if( UserManager::getInstance()->validateRecoveryToken($_GET['token']) ) {
			$step = 3;
		}
		else {
			$error = "The given token is invalid or outdated!";
		}
	}
	else if( isset($_POST['recover_user_name']) || isset($_POST['recover_email'])) {
		
		if( $_POST['recover_user_name'] ) {
			try {
				UserManager::getInstance()->sendRecoveryEmail(UserDatabase::getInstance()->getUserIdForName($_POST['recover_user_name']));
				$step = 2;
			}
			catch( DoesNotExistException $dnee ) {
				$error = "No user account was found for the user name {$_POST['recover_user_name']}!";
			}
		}
		else if( $_POST['recover_email'] ) {
			try {
				UserManager::getInstance()->sendRecoveryEmail(UserDatabase::getInstance()->getUserIdForEmail($_POST['recover_email']));
				$step = 2;
			}
			catch( DoesNotExistException $dnee ) {
				$error = "No user account was found for the e-mail address {$_POST['recover_email']}!";
			}
		}
		else {
			$error = "Please specify either your e-mail address or your user name!";
		}
	}
	
	$locale = chardev\Language::getInstance()->getLocaleArray();
	
	if( $step == 1 ) {
		$form = new chardev\frontend\Form("RecoverPassword.html");
		
		if( $error ) {
			$form->addError($error);
			$error = null;
		}
		
		$form->addInput( $locale['User_name'], "recover_user_name");
		$form->addInput( "E-Mail", "recover_email");
		$form->addSubmit("Recover");
	}
	else if( $step == 3 ) {
		$form = new chardev\frontend\Form("RecoverPassword.html");
			
		if( $error ) {
			$form->addError($error);
			$error = null;
		}
			
		$n = $form->addPassword( $locale['New_Password'], "recover_new_password", "alnum,min=4");
		$form->addSecret( $locale['Repeat'], "", "repeat of {$n}");
		$form->addSubmit("Change Password");
		$form->addHidden( "recover_token", $_GET['token']);
	}
?>

<div class="content_wrapper">
	<h1>Recover Password</h1>
	<div class="fm_err"><?php echo $error ?></div>
<?php 
	switch($step): 
		case 1:
			echo $form->getHtml();
			break;
		case 2: ?>
			<div>
				<div class='fm_note'>An e-mail was sent, follow the link to change your password.</div>  
			</div>
<?php 		break;
		case 3: 
			echo $form->getHtml();
			break;
endswitch; ?>


</div>